version: "3"

services:
  traefik:
    image: traefik:2.10
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
  whoami:
    image: traefik/whoami
    container_name: whoami
