- name: Create Portainer volume
  community.docker.docker_volume:
    name: portainer_data
    state: present

# This is a dirty hack to get around the fact that Portainer doesn't support relative paths for volume mounts
- name: Symlinking Portainer volume
  file:
    src: /var/lib/docker/volumes/portainer_data/_data
    dest: /data
    state: link

- name: Start Portainer container
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    state: started
    restart_policy: always
    ports:
      - 9443:9443
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
