- hosts: k3s_lbs
  become: true
  roles:
    - load_balancer

- hosts: k3s_clb_0
  become: true
  roles:
    - k3s/cluster_load_balancer
  vars:
    keepalived_state: MASTER
    keepalived_priority: 500

- hosts: k3s_clb_1
  become: true
  roles:
    - k3s/cluster_load_balancer
  vars:
    keepalived_state: BACKUP
    keepalived_priority: 100

- hosts: k3s_init_server
  roles:
    - k3s/init_server

- hosts: localhost
  tasks:
    - name: Set kubeconfig cluster server
      lineinfile:
        path: ~/.kube/config
        search_string: "server: https://"
        line: "    server: https://10.10.3.93:6443"

- hosts: k3s_servers
  roles:
    - k3s/server

- hosts: k3s_agents
  roles:
    - k3s/agent
