- hosts: k3s-lb-1
  become: true
  roles:
    - load_balancer
    - k3s/load_balancer
  vars:
    keepalived_state: MASTER
    keepalived_priority: 200

- hosts: k3s-lb-2
  become: true
  roles:
    - load_balancer
    - k3s/load_balancer
  vars:
    keepalived_state: BACKUP
    keepalived_priority: 100

- hosts: k3s-server-1
  roles:
    - k3s/init_server

- hosts: localhost
  tasks:
    - name: Set kubeconfig cluster server
      lineinfile:
        path: ~/.kube/config
        search_string: "server: https://"
        line: "    server: https://10.10.3.100:6443"

- hosts: k3s_servers
  roles:
    - k3s/server
