services:
  dozzle:
    image: amir20/dozzle:latest
    restart: unless-stopped
    environment:
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_REMOTE_AGENT=10.10.3.21:7007
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend
    healthcheck:
      test:
        - CMD
        - /dozzle
        - healthcheck
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`dozzle.olym.foo`)

networks:
  frontend:
    external: true
