k3s_init_server:
  hosts:
    k3s-server-0:
      ansible_host: 10.10.3.101

k3s_servers:
  hosts:
    k3s-server-1:
      ansible_host: 10.10.3.102
    k3s-server-2:
      ansible_host: 10.10.3.103

k3s_agents:
  hosts:
    k3s-agent-0:
      ansible_host: 10.10.3.111
    k3s-agent-1:
      ansible_host: 10.10.3.112
    k3s-agent-2:
      ansible_host: 10.10.3.113

k3s_hosts:
  children:
    k3s_init_server:
    k3s_servers:
    k3s_agents:
