all:
  vars:
    ansible_user: debian
    k3s_token: SECRET
    k3s_lb_vip: 10.10.3.100

k3s_lbs:
  hosts:
    k3s-lb-1:
      ansible_host: 10.10.3.98
      keepalived_state: MASTER
      keepalived_priority: 200
    k3s-lb-2:
      ansible_host: 10.10.3.99
      keepalived_state: BACKUP
      keepalived_priority: 100

k3s_servers:
  hosts:
    k3s-server-1:
      ansible_host: 10.10.3.101
    k3s-server-2:
      ansible_host: 10.10.3.102
    k3s-server-3:
      ansible_host: 10.10.3.103
