all:
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

director:
  hosts:
    manager-00:
      ansible_host: 10.10.3.101

managers:
  children:
    director:

workers:
  hosts:
    worker-00:
      ansible_host: 10.10.3.111

k8s_hosts:
  children:
    managers:
    workers:
